// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtMDYhQPaxVttHx-x0is1MMpivAO3Vs5o',
    appId: '1:236523224662:web:0b5eb175cdb66fb7cb45f7',
    messagingSenderId: '236523224662',
    projectId: 'luna-pets-anywhere',
    authDomain: 'luna-pets-anywhere.firebaseapp.com',
    storageBucket: 'luna-pets-anywhere.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt6hnJG1RHCrpyqyZEXY6kqtglXjdaRrU',
    appId: '1:236523224662:android:0ecb96e93f8ebe96cb45f7',
    messagingSenderId: '236523224662',
    projectId: 'luna-pets-anywhere',
    storageBucket: 'luna-pets-anywhere.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrRSC0vOo_8Of9AIptL6va0n0COtV5wgc',
    appId: '1:236523224662:ios:5d65613ef2003716cb45f7',
    messagingSenderId: '236523224662',
    projectId: 'luna-pets-anywhere',
    storageBucket: 'luna-pets-anywhere.appspot.com',
    iosBundleId: 'com.example.lunaDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrRSC0vOo_8Of9AIptL6va0n0COtV5wgc',
    appId: '1:236523224662:ios:59a7670937d23189cb45f7',
    messagingSenderId: '236523224662',
    projectId: 'luna-pets-anywhere',
    storageBucket: 'luna-pets-anywhere.appspot.com',
    iosBundleId: 'com.example.lunaDemo.RunnerTests',
  );
}
